name: Production Build and Deploy
on:
  push:
    branches: [ main ]
    paths-ignore:
      - '.github/workflows/**'
      - '**.md'

jobs:
  build:
    runs-on: ubuntu-latest
    environment:
      name: production
      url: ${{ secret.DEPLOYMENT_URL }}
    steps:
      - name: Setup Node.js
        uses: actions/setup-node@v2
      
      # https://github.com/actions/checkout#push-a-commit-using-the-built-in-token
      - name: Set GitHub Actions as Commit Author
        run: |
          git config --global user.name github-actions
          git config --global user.email github-actions@github.com
          
      - name: Checkout Repo
        uses: actions/checkout@v2
        with:
          path: 'build'
      
      - name: Build
        run: |
          cd build
          yarn
          export API_URL=${{ secret.API_URL }}
          export GITHUB_CLIENT_ID=79c2b8f305ad223cfb5e
          export OPENQ_ADDRESS=0xEC1dA9EeE346A67C121E4fce746C64b4e31b61A4
          export CHAIN_ID=42
          yarn app:generate
          cd ..
      
      - name: Checkout Prod Target
        uses: actions/checkout@v2
        with:
          repository: ${{ secrets.DEPLOYMENT_REPO }}
          path: 'deploy'
          token: ${{ secrets.PAT }}
      
      - name: Push files to target
        run: |
          cp -r build/dist/* deploy
          cd deploy
          touch .nojekyll
          echo ${{ secret.CNAME }} > CNAME
          git add .
          git commit -m $GITHUB_SHA
          git push
